name: CI-CD Django

on:
  push:
    branches: ["main"]

jobs:
  build-and-update-argocd:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout du repo Django
      - name: Checkout Django code
        uses: actions/checkout@v3

      # 2. Login Docker
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build et push de l'image Docker
      - name: Build Docker image
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/django-app
          docker build -t $IMAGE:${{ github.sha }} .
          docker push $IMAGE:${{ github.sha }}

      # 4. Checkout du repo ArgoCD pour mise à jour
      - name: Checkout ArgoCD repo
        uses: actions/checkout@v3
        with:
          repository: ngueagho/argocd
          token: ${{ secrets.ARGOCD_PAT }}
          path: argocd-repo  # clone dans ce dossier

      # 5. Mettre à jour le manifeste Kubernetes dans ArgoCD repo
      - name: Update Kubernetes deployment image
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/django-app:${{ github.sha }}
          sed -i "s|image: .*|image: $IMAGE|" argocd-repo/k8s/deployment.yaml

      # 6. Commit et push vers ArgoCD repo
      - name: Commit changes to ArgoCD repo
        run: |
          cd argocd-repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          # Forcer le remote à utiliser le PAT
          git remote set-url origin https://x-access-token:${{ secrets.ARGOCD_PAT }}@github.com/ngueagho/argocd.git
          git add k8s/deployment.yaml
          git commit -m "Update image to $IMAGE"
          git push origin main






