name: django app deploy's workflow 

on:
  push:
    branches: [main]    

jobs:
  deploy:  
    runs-on: ubuntu-latest
    steps:
      - name: clone the code 
        uses: actions/checkout@v3

            

